Ticket_Booking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . views import my_html_page 
from trains.views import ticket_booking
urlpatterns = [
    path('admin/', admin.site.urls),
    path('passengers/', include('passengers.urls')),
    path('', ticket_booking,name='home'), 
    path('trains/',include('trains.urls')), 
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

trains/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from . views import train_create_view,TrainUpdateView,TrainListView,TrainDeleteView,Home,leave_review

urlpatterns = [
    path('add_train/',train_create_view,name='add_train'), 
    path('edit/<int:pk>/', TrainUpdateView.as_view(), name='train_edit'),
    path('admin_dashboard/', TrainListView.as_view(), name='admin_dashboard'), 
    path('train/<int:pk>/delete/', TrainDeleteView.as_view(), name='train_delete'), 
    path('train_details',Home.as_view(), name='train_details'),
    path('station_filtering/<slug:category_slug>/', Home.as_view(), name='station_filtering'), 
    path('train/review/<int:id>/',leave_review,name='leave_review'),
] 
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

trains/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.utils import timezone
# Create your models here.
SEAT_CHOICES = [
    ('AC_B','AC_B'),
    ('AC_S','AC_S'),
    ('SNIGDHA','SNIGDHA'),
    ('S_CHAIR','S_CHAIR'),
    ('SHULOV','SHULOV'),
    ('F_SEAT','F_SEAT'),
]
class Station(models.Model):
    station_name = models.CharField(max_length = 100,default = '') 
    slug = models.SlugField(max_length=100,unique=True, null=True, blank=True) 

    def __str__(self):
        return self.station_name  
    
class Train(models.Model): 
    station_name = models.ForeignKey(Station, related_name='origin_station', on_delete=models.CASCADE )
    train_number = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100 ,default = '')
    origin = models.CharField(max_length=100,default = '')
    destination = models.CharField(max_length=100,default = '')
    departure_time = models.TimeField()
    arrival_time = models.TimeField() 
    ticket_price = models.PositiveIntegerField()
    train_pic = models.ImageField(upload_to='passengers/media/uploads/',null = True, blank=True) 
    total_seats = models.PositiveIntegerField()
    available_seats = models.PositiveIntegerField() 
    

    def __str__(self):
        return f"{self.train_number} - {self.name}"

    class Meta:
        ordering = ['departure_time'] 



class TicketBooking(models.Model): 
    user = models.ForeignKey(User, on_delete = models.CASCADE,blank=True, null = True)
    train = models.ForeignKey(Train, on_delete = models.CASCADE,blank=True, null = True)
    From = models.CharField(max_length = 100) 
    to = models.CharField(max_length = 100) 
    date = models.DateField() 
    tickets = models.PositiveIntegerField() 
    choose_class = models.CharField(choices= SEAT_CHOICES,default = '')

    def __str__(self) -> str:
        return f'From {self.From} to {self.to}' 

class Review(models.Model):
    train = models.ForeignKey(Train,related_name ='review', on_delete = models.CASCADE) 
    user_review = models.ForeignKey(User,on_delete=models.CASCADE,related_name ='user_review')
    content = models.TextField()
    rating = models.PositiveIntegerField() 
    created_on =models.DateTimeField(default =timezone.now)
    
    def __str__(self):
        return f"Comments by {self.user_review.username}"

    

trains/forms.py
from django import forms
from .models import Train 
from .models import TicketBooking,Review
from django.core.exceptions import ValidationError

class TrainForm(forms.ModelForm):

    class Meta:
        model = Train
        fields = '__all__'
        widgets = {
            
            'train_pic': forms.ClearableFileInput(attrs={'value': '{{ form.train_pic.value }}'})
        
        } 


class TicketBookingForm(forms.ModelForm):
    
    class Meta:
        model = TicketBooking
        fields = ['From', 'to', 'date', 'tickets','choose_class'] 
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date','placeholder':'Pick a date'}),
             'choose_class':forms.Select(attrs={'class':' bg-gray-500 text-white border border-green-500 rounded-md p-2 w-full','placeholder':'Choose class'})
        } 
    
    def clean_tickets(self):
        tickets = self.cleaned_data.get('tickets')

        if tickets is not None:
            if tickets < 1 or tickets > 3:
                raise ValidationError("You can only buy between 1 and 3 tickets.")

        return tickets 

class ClientReview(forms.ModelForm):
    class Meta:
        model = Review 
        fields = ['content','rating']
    

trains/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import Train,TicketBooking
from passengers.models import AccountModel
from .forms import TrainForm,TicketBookingForm,ClientReview
from django.views.generic import ListView
from django.views.generic.edit import UpdateView 
from django.views.generic import DeleteView  
from . models import TicketBooking 
from django.contrib import messages 
from . models import Train, Station,Review  
from django.contrib.auth.mixins import AccessMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test  
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
class SuperuserRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('home')  # Redirect non-superusers to the home page
        return super().dispatch(request, *args, **kwargs)
# Create your views here.

@staff_member_required
def train_create_view(request):
    if request.method == 'POST':
        form = TrainForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Train information added successfully!")
            return redirect('admin_dashboard')
        
    else:
        form = TrainForm()
    
    context = {
        'form': form,
        'type': 'ADD A NEW TRAIN INFORMATION'
    }
    
    return render(request, 'trains/train_list.html', context)
   

class TrainListView(SuperuserRequiredMixin,ListView):
    model = Train
    template_name = 'trains/admin_dashboard.html' 
    context_object_name = 'trains'

class TrainUpdateView(SuperuserRequiredMixin,UpdateView):
    model = Train
    template_name = 'trains/train_edit.html'  
    fields = '__all__'
    success_url = reverse_lazy('home')   
    def get_initial(self):
        initial = super().get_initial()
        instance = self.object
        if instance:
            initial['train_pic'] = instance.train_pic
        return initial
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'EDIT TRAIN INFORMATION'  
        return context 
    def form_valid(self, form):
        messages.success(self.request, "Train information updated successfully!")
        return super().form_valid(form)

class TrainDeleteView(SuperuserRequiredMixin,DeleteView):
    model = Train
    template_name = 'trains/train_confirm_delete.html'
    success_url = reverse_lazy('admin_dashboard')
    context_object_name = 'train' 
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Train information deleted successfully!")
        return super().delete(request, *args, **kwargs)


def ticket_booking(request):
    reviews = Review.objects.all()
    if request.method == 'POST':
        form = TicketBookingForm(request.POST)
        if form.is_valid():
            from_location = form.cleaned_data['From'] 
            to = form.cleaned_data['to']
            date = form.cleaned_data['date']
            tickets = form.cleaned_data['tickets'] 
            choose_class = form.cleaned_data['choose_class']
            acc = None
            try:
                train_obj = Train.objects.get(origin=from_location, destination=to) 
                total_price = tickets * train_obj.ticket_price 
                try:
                    acc = AccountModel.objects.get(user_acc = request.user) 
                

                      
                    if acc.total_buyed_tickets > 3: 
                        messages.error(request, "Oops! You've already purchased 3 tickets. To ensure fair access, we limit purchases to a maximum of 3 tickets per transaction. Thank you.")
                    
                    elif total_price <= acc.balance:
                        acc.balance -= total_price
                        if train_obj.available_seats >= tickets:
                            train_obj.available_seats -= tickets 
                            acc.total_buyed_tickets += tickets
                            train_obj.save() 
                            acc.save() 
                            TicketBooking.objects.create( 
                                user = request.user,
                                train = train_obj,
                                From=from_location,
                                to=to,
                                date=date,
                                tickets=tickets,
                                choose_class = choose_class
                            )
                            messages.success(request, f"Success! You have successfully purchased {tickets} tickets from {from_location} to {to} in {choose_class} class for {date}.Your booking is confirmed. We appreciate your trust in our ticket booking service. Wishing you a safe and pleasant journey!")

                            return redirect('home')  
                        else:
                            messages.error(request, f"There are not enough available seats on the train for {choose_class} class.")
                            return redirect('home')
                    else: 
                        messages.error(request, f"You don't have sufficient balance to buy tickets.") 
                except AccountModel.DoesNotExist:
                    messages.error(request, 'An account is required to proceed. Please make a deposit to create your account.')

            except Train.DoesNotExist:
                messages.error(request, f'Enter valid location')

    else:
        form = TicketBookingForm()

    return render(request, 'base.html', {'form': form, 'reviews':reviews}) 

class Home(ListView):
    model = Train
    template_name = 'trains/station_filter.html' 
    context_object_name = 'trains' 
    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        if category_slug:
         category = Station.objects.get(slug=category_slug)
         return Train.objects.filter(station_name=category) 
        else:
         return Train.objects.all() 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['station'] = Station.objects.all()
        return context
@login_required
def leave_review(request,id):
    train = get_object_or_404(Train, id=id)
    existing_review = Review.objects.filter(train=train, user_review=request.user).first() 
    buy_or_not = TicketBooking.objects.filter(train=train, user=request.user).exists() 
    if existing_review:
        messages.info(request, 'You have already reviewed this Train.')
        return redirect('profile')
    elif buy_or_not is False: 
        messages.warning(request, 'You need to buy a ticket to leave a review.')
        return redirect('home') 
    else:
        if request.method == 'POST':
            form = ClientReview(request.POST)
            if form.is_valid():
                content = form.cleaned_data['content']
                rating = form.cleaned_data['rating']
            
                Review.objects.create(train=train, user_review=request.user, content=content, rating=rating)
            
                messages.success(request, 'Thank you for your review!')
                return redirect('home')
        else:
            form = ClientReview() 
        return render(request, 'trains/leave_review.html', {'form': form})

        
    
        
    

    

trains/templates/trains/admin_dashboard.html
<!-- admin_dashboard.html -->

{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto p-4 md:p-8 mb-20 ">
    <h1 class="text-2xl md:text-3xl font-bold mb-4 md:mb-8">Admin Dashboard - Train List</h1>
    <a href="{% url 'add_train' %}"
        class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700 block md:inline-block md:mb-4 w-full md:w-auto text-center">Add
        New Train</a>
    <div class="bg-white rounded-lg shadow-md overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
                <tr>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Train
                        Number</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Name</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Origin
                    </th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Destination</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Departure
                        Time</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Arrival
                        Time</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Ticket Price</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Total
                        Seats</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Available
                        Seats</th>
                    <th scope="col"
                        class="px-4 md:px-6 py-3 text-left text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wider">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
                {% for train in trains %}
                <tr>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.train_number }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.name }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.origin }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.destination }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.departure_time }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.arrival_time }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.ticket_price }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.total_seats }}</td>
                    <td class="px-4 md:px-6 py-4 whitespace-nowrap">{{ train.available_seats }}</td>

                    <td class="flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-2">
                        <a href="{% url 'train_edit' train.pk %}"
                            class="bg-blue-400 hover:bg-blue-600 text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline transition duration-300 ease-in-out">

                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="bg-white" height="40"
                                width="40">
                                <path
                                    d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152V424c0 48.6 39.4 88 88 88H360c48.6 0 88-39.4 88-88V312c0-13.3-10.7-24-24-24s-24 10.7-24 24V424c0 22.1-17.9 40-40 40H88c-22.1 0-40-17.9-40-40V152c0-22.1 17.9-40 40-40H200c13.3 0 24-10.7 24-24s-10.7-24-24-24H88z" />
                            </svg>
                        </a>
                        <a href="{% url 'train_delete' pk=train.pk %}"
                            class="bg-red-500 hover:bg-red-600 text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline mt-2 md:mt-0 transition duration-300 ease-in-out">

                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512 " height="40" width="40"
                                style="background-color: aliceblue; display: block; margin: auto;">
                                <path
                                    d="M170.5 51.6L151.5 80h145l-19-28.4c-1.5-2.2-4-3.6-6.7-3.6H177.1c-2.7 0-5.2 1.3-6.7 3.6zm147-26.6L354.2 80H368h48 8c13.3 0 24 10.7 24 24s-10.7 24-24 24h-8V432c0 44.2-35.8 80-80 80H112c-44.2 0-80-35.8-80-80V128H24c-13.3 0-24-10.7-24-24S10.7 80 24 80h8H80 93.8l36.7-55.1C140.9 9.4 158.4 0 177.1 0h93.7c18.7 0 36.2 9.4 46.6 24.9zM80 128V432c0 17.7 14.3 32 32 32H336c17.7 0 32-14.3 32-32V128H80zm80 64V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16z" />
                            </svg>
                        </a>
                    </td>


                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

trains/templates/trains/train_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="max-w-lg mx-auto my-8 bg-gradient-to-br from-red-500 via-red-600 to-red-700 p-10 rounded-lg shadow-lg">
    <h2 class="text-3xl font-bold text-white mb-4">Confirm Deletion</h2>
    <p class="text-white mb-6">Are you sure you want to delete "{{ train.name }}"?</p>

    <form method="post" action="{% url 'train_delete' pk=train.pk %}" class="mb-6">
        {% csrf_token %}
        <button type="submit"
            class="bg-gradient-to-br from-red-500 via-red-600 to-red-700 hover:from-red-600 hover:via-red-700 hover:to-red-800 text-white py-2 px-4 rounded-full focus:outline-none focus:shadow-outline transition duration-300 ease-in-out">
            Yes, delete
        </button>
    </form>

    <a href="{% url 'home' %}" class="text-blue-500 hover:text-blue-600">Cancel</a>
</div>
{% endblock %}

trains/templates/trains/train_edit.html
{% extends 'base.html' %}

{% block content %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %}
{% endif %}

<div class="bg-blue-300 px-3 py-4 rounded-xl my-6">
    <h1 class="font-bold text-3xl text-center pb-5">{{type}}</h1>
    <div class="w-full mt-10">
        <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
            {% endfor %}

            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label for="id_station_name"
                        class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Station name:</label>
                    {{ form.station_name }}
                </div>


                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.name.id_for_label }}">
                        {{ form.name.label }}
                    </label>


                    <input type="text" name="{{ form.name.name }}" value="{{ form.name.value}}"
                        id="{{ form.name.id_for_label }}" placeholder="Enter your train name"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.name.errors %}
                    {% for error in form.name.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>

                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.train_number.id_for_label }}">
                        {{ form.train_number.label }}
                    </label>


                    <input type="number" name="{{ form.train_number.name }}" value="{{ form.train_number.value }}"
                        id="{{ form.train_number.id_for_label }}" placeholder="Enter train number"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.train_number.errors %}
                    {% for error in form.train_number.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.origin.id_for_label }}">
                        {{ form.origin.label }}
                    </label>

                    {# Customize the rendering of the input field #}
                    <input type="text" name="{{ form.origin.name }}" value="{{ form.origin.value }}"
                        id="{{ form.origin.id_for_label }}" placeholder="Enter train origin"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.origin.errors %}
                    {% for error in form.origin.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.destination.id_for_label }}">
                        {{ form.destination.label }}
                    </label>

                    {# Customize the rendering of the input field #}
                    <input type="text" name="{{ form.destination.name }}" value="{{ form.destination.value }}"
                        id="{{ form.destination.id_for_label }}" placeholder="Enter train destination"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.destination.errors %}
                    {% for error in form.destination.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.departure_time.id_for_label }}">
                        {{ form.departure_time.label }}
                    </label>

                    {# Customize the rendering of the input field #}
                    <input type="time" name="{{ form.departure_time.name }}" value="{{ form.departure_time.value }}"
                        id="{{ form.departure_time.id_for_label }}"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.departure_time.errors %}
                    {% for error in form.departure_time.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.arrival_time.id_for_label }}">
                        {{ form.arrival_time.label }}
                    </label>

                    {# Customize the rendering of the input field #}
                    <input type="time" name="{{ form.arrival_time.name }}" value="{{ form.arrival_time.value }}"
                        id="{{ form.arrival_time.id_for_label }}"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.arrival_time.errors %}
                    {% for error in form.arrival_time.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.total_seats.id_for_label }}">
                        {{ form.total_seats.label }}
                    </label>

                    {# Customize the rendering of the input field #}
                    <input type="number" name="{{ form.total_seats.name }}" value="{{ form.total_seats.value }}"
                        id="{{ form.total_seats.id_for_label }}" placeholder="Enter total seat"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.total_seats.errors %}
                    {% for error in form.total_seats.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.available_seats.id_for_label }}">
                        {{ form.available_seats.label }}
                    </label>


                    <input type="number" name="{{ form.available_seats.name }}" value="{{ form.available_seats.value }}"
                        id="{{ form.available_seats.id_for_label }}" placeholder="Enter available seats"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.available_seats.errors %}
                    {% for error in form.available_seats.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.ticket_price.id_for_label }}">
                        {{ form.ticket_price.label }}
                    </label>
                    <input type="number" name="{{ form.ticket_price.name }}" value="{{ form.ticket_price.value }}"
                        id="{{ form.ticket_price.id_for_label }}" placeholder="Enter ticket price"
                        class="border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline">

                    {% if form.ticket_price.errors %}
                    {% for error in form.ticket_price.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0 mt-2">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                        for="{{ form.train_pic.id_for_label }}">
                        {{ form.train_pic.label }}
                    </label>
                    {{form.train_pic}}

                    {% if form.train_pic.errors %}
                    {% for error in form.train_pic.errors %}
                    <p class="text-red-600 text-sm italic pb-2">
                        {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="flex items-center justify-between">
                <button
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-7 rounded focus:outline-none focus:shadow-outline"
                    type="submit">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}